# Generated by Django 4.2.5 on 2023-09-26 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodie", "0005_remove_review_order_order_reviews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="item",
        ),
    ]
